### ISSUE TITLE
Nothing happens on shift + click on a stamp maker

### ISSUE THREAD

**Issue by vanlueckn** [AviatorRob/disx#2]
**Describe the bug**
I am unable to open the ui to enter a video id.

**Steps To Reproduce**
1. Place stamp maker with block of laquer
2. Shift + left click on it
3. Nothing happens

**Logs**
No entries in the log

**Mod Loader**
Fabric, Forge, or Quilt?
- Forge 47.3.12

**Minecraft Version**
Pick from the one option available!
- 1.20.1

**Additional context**
DisX b0.1.2 
Screen Recording: https://[img.vanlueck.dev/NaDBeaShbYd0/direct](https://img.vanlueck.dev/NaDBeaShbYd0/direct)

**Comment by aviatorrob06** [comment]
Hi @vanlueckn,

Remove the shield from your off-hand, then try again. Due to the way Mojang designed items, especially the shield, having any items in your hand or off-hand and shift clicking prioritizes what the item is designed to do, so it doesn't set off the targeted block properly. Also, make sure you are right clicking (as in using/placing) and not punching (as in destroying). I plan on replacing shift + click eventually with something else to streamline the process a bit, but for now please bear with me and I apologize for the confusion and inconvenience.

EDIT: I will also add I discovered a bug in some testing yesterday that impacts the renderer on the Stamp Maker (what makes lacquer blocks appear inside of it) which causes it to not disappear when the Stamp Maker produces a Record Stamp. The Lacquer Block is consumed in the process as it should be, it's just a bug with the renderer, so no duplication of Lacquer Blocks will occur. Just figured I'd inform you that I know of this bug so you don't have to report it if you encounter it, and it will be patched in the next release. :)

Hope that helps,
Aviator_Rob

**Comment by vanlueckn** [comment]
Hi @AviatorRob,

thank your for your answer. 

I removed my shield. Now the stamp maker despawns if i shift right-click it and this error gets printed to my console:

```
[18:05:05] [Render thread/ERROR] [ne.mi.cl.gu.ov.ForgeGui/]: Error rendering overlay 'minecraft:chat_panel'
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?] {re:mixin}
	at wayoftime.bloodmagic.compat.CuriosCompat.getCuriosInventory(CuriosCompat.java:26) ~[bloodmagic-1.20.1-3.3.3-45.jar%23478!/:1.20.1-3.3.3-45] {re:classloading}
	at wayoftime.bloodmagic.compat.CuriosCompat.lambda$registerInventory$0(CuriosCompat.java:20) ~[bloodmagic-1.20.1-3.3.3-45.jar%23478!/:1.20.1-3.3.3-45] {re:classloading}
	at wayoftime.bloodmagic.util.helper.InventoryHelper.lambda$getActiveInventories$2(InventoryHelper.java:75) ~[bloodmagic-1.20.1-3.3.3-45.jar%23478!/:1.20.1-3.3.3-45] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at wayoftime.bloodmagic.util.helper.InventoryHelper.getActiveInventories(InventoryHelper.java:75) ~[bloodmagic-1.20.1-3.3.3-45.jar%23478!/:1.20.1-3.3.3-45] {re:classloading}
	at wayoftime.bloodmagic.util.Utils.canPlayerSeeDemonWill(Utils.java:576) ~[bloodmagic-1.20.1-3.3.3-45.jar%23478!/:1.20.1-3.3.3-45] {re:classloading}
	at wayoftime.bloodmagic.client.hud.element.ElementDemonAura.shouldRender(ElementDemonAura.java:78) ~[bloodmagic-1.20.1-3.3.3-45.jar%23478!/:1.20.1-3.3.3-45] {re:classloading}
	at wayoftime.bloodmagic.client.hud.ElementRegistry.onRenderOverlay(ElementRegistry.java:140) ~[bloodmagic-1.20.1-3.3.3-45.jar%23478!/:1.20.1-3.3.3-45] {re:classloading}
	at wayoftime.bloodmagic.client.hud.__ElementRegistry_onRenderOverlay_Pre.invoke(.dynamic) ~[bloodmagic-1.20.1-3.3.3-45.jar%23478!/:1.20.1-3.3.3-45] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.client.gui.overlay.ForgeGui.pre(ForgeGui.java:643) ~[forge-1.20.1-47.3.12-universal.jar%23745!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:gui.MixinForgeGui,pl:mixin:APP:healthindicatortxf.mixins.json:GuiMixin,pl:mixin:APP:betterf3.forge.mixins.json:ForgeGuiMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.debug.ForgeGuiMixin,pl:mixin:APP:immediatelyfast-forge.mixins.json:hud_batching.MixinForgeGui,pl:mixin:A}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:125) ~[forge-1.20.1-47.3.12-universal.jar%23745!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:gui.MixinForgeGui,pl:mixin:APP:healthindicatortxf.mixins.json:GuiMixin,pl:mixin:APP:betterf3.forge.mixins.json:ForgeGuiMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.debug.ForgeGuiMixin,pl:mixin:APP:immediatelyfast-forge.mixins.json:hud_batching.MixinForgeGui,pl:mixin:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23102!/:?] {re:mixin}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121) ~[forge-1.20.1-47.3.12-universal.jar%23745!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:gui.MixinForgeGui,pl:mixin:APP:healthindicatortxf.mixins.json:GuiMixin,pl:mixin:APP:betterf3.forge.mixins.json:ForgeGuiMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.debug.ForgeGuiMixin,pl:mixin:APP:immediatelyfast-forge.mixins.json:hud_batching.MixinForgeGui,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:945) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin,pl:mixin:APP:exposure-common.mixins.json:DrawViewfinderOverlayMixin,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin,pl:mixin:APP:create_train_perspective.mixins.json:GameRendererMixin,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin,pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer,pl:mixin:APP:rrls.mixins.json:compat.GameRendererMixin,pl:mixin:APP:rrls.mixins.json:compat.RendererKeyboardMouseMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:APP:forge-badoptimizations.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23740!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}```

**Comment by aviatorrob06** [comment]
Hello @vanlueckn,

Upon evaluation of the log you provided, it appears there may be an unknown mod incompatibility with Disx. Would you be able to send me a list of or copy of your modpack? Furthermore, was this on a singleplayer (local) world, or was this on a server?

Note: If needed, you can send it via the [aviatorrob06 Discord Server](http://discord.ar06.xyz).

Thanks,
Aviator_Rob

**Comment by vanlueckn** [comment]
It was carry on, my fault

**Comment by aviatorrob06** [comment]
All good. Glad you figured it out.
